# Generated by Django 3.1.1 on 2020-09-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('contract_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('banking', models.BooleanField()),
                ('bonus', models.BooleanField()),
                ('bike_stands', models.IntegerField()),
                ('available_bike_stands', models.IntegerField()),
                ('available_bikes', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=200)),
                ('last_update', models.IntegerField()),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='velose.position')),
            ],
        ),
    ]
