# Generated by Django 3.1.1 on 2020-09-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velose', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AlterField(
            model_name='position',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='position',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=200, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='station',
            name='available_bike_stands',
            field=models.IntegerField(verbose_name='bornes dispos'),
        ),
        migrations.AlterField(
            model_name='station',
            name='available_bikes',
            field=models.IntegerField(verbose_name='velos dispos'),
        ),
        migrations.AlterField(
            model_name='station',
            name='bike_stands',
            field=models.IntegerField(verbose_name='bornes'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='station',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
