# Generated by Django 3.1.1 on 2020-10-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('contract_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('address', models.CharField(max_length=200, verbose_name='adresse')),
                ('banking', models.BooleanField()),
                ('bonus', models.BooleanField()),
                ('bike_stands', models.IntegerField(verbose_name='bornes')),
                ('available_bike_stands', models.IntegerField(verbose_name='bornes dispos')),
                ('available_bikes', models.IntegerField(verbose_name='velos dispos')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=200)),
                ('last_update', models.DateTimeField(verbose_name='dernière mise-à-jour')),
                ('starred', models.BooleanField()),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='velouse.position')),
            ],
        ),
    ]
